# Air configuration for hot reloading
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"
# ------------------------------------------------

# WINDOWS CMD USERS:
# uncomment this block if using Windows CMD# [build]
# cmd = "go build -o main.exe -mod=mod -buildvcs=false ."
# bin = "main.exe"
# full_bin = "main.exe"
# ------------------------------------------------

# WSL2 / LINUX USERS:
# uncomment this block if using WSL2 or native Linux
[build]
cmd = "go build -o tmp/main -mod=mod -buildvcs=false ."
bin = "tmp/main"
full_bin = "tmp/main"
# ------------------------------------------------

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "testdata", ".git"]
include_dir = []
exclude_file = []
log = "air.log"
delay = 1000
stop_on_root = false
send_interrupt = false
kill_delay = "0.5s"

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true