global:
  scrape_interval: 5s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: "film_go_service"
    static_configs:
      - targets: ["host.docker.internal:9090"] # if Go service runs outside Docker

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
